name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
      run: |
        echo $ANDROID_KEYSTORE_PASSWORD >> secrets.txt
        echo $ANDROID_KEYSTORE >> secrets.txt
        echo $RCLONE_CONFIG >> secrets.txt
    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
